/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas_222212787.View;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import java.sql.*;
import javax.swing.*;

//import latihan.gui.EntryPanel;
//import latihan.gui.LoginPanel;

/**
 *
 * @author Nazlya
 */
public class MainFrame extends javax.swing.JFrame {
    private boolean isLoggedIn = false;  
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        setTitle("APEKA SM");
        initComponents();
        contentScrollPane.setViewportView(new LoginPanel(contentScrollPane, this));
    }
    
    public void setLoggedIn(boolean isLoggedIn) {
        this.isLoggedIn = isLoggedIn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contentScrollPane = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        homeMenu = new javax.swing.JMenu();
        backHomeMenuItem = new javax.swing.JMenuItem();
        entriMenu = new javax.swing.JMenu();
        anggotaMenuItem = new javax.swing.JMenuItem();
        nilaiMenuItem = new javax.swing.JMenuItem();
        logoutMenu = new javax.swing.JMenu();
        logoutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1424;
        gridBagConstraints.ipady = 731;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(contentScrollPane, gridBagConstraints);

        homeMenu.setText("Home");
        homeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeMenuActionPerformed(evt);
            }
        });

        backHomeMenuItem.setText("Back To Home");
        backHomeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backHomeMenuItemActionPerformed(evt);
            }
        });
        homeMenu.add(backHomeMenuItem);

        jMenuBar1.add(homeMenu);

        entriMenu.setText("Entri");

        anggotaMenuItem.setText("Anggota");
        anggotaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anggotaMenuItemActionPerformed(evt);
            }
        });
        entriMenu.add(anggotaMenuItem);

        nilaiMenuItem.setText("Nilai Anggota");
        nilaiMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiMenuItemActionPerformed(evt);
            }
        });
        entriMenu.add(nilaiMenuItem);

        jMenuBar1.add(entriMenu);

        logoutMenu.setText("Logout");
        logoutMenu.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        logoutMenuItem.setText("Keluar Aplikasi");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        logoutMenu.add(logoutMenuItem);

        jMenuBar1.add(logoutMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anggotaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anggotaMenuItemActionPerformed
        // TODO add your handling code here:
        if (isLoggedIn) {
            contentScrollPane.setViewportView(new EntriPanel());
        } else {
            JOptionPane.showMessageDialog(this, "Silahkan Login dahulu!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_anggotaMenuItemActionPerformed

    private void nilaiMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiMenuItemActionPerformed
        // TODO add your handling code here:
        if (isLoggedIn) {
            contentScrollPane.setViewportView(new NilaiPanel());
        } else {
            JOptionPane.showMessageDialog(this, "Silahkan Login dahulu!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_nilaiMenuItemActionPerformed

    private void homeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeMenuActionPerformed
        // TODO add your handling code here:
        if (isLoggedIn) {
            contentScrollPane.setViewportView(new homePanel());
        } else {
            JOptionPane.showMessageDialog(this, "Silahkan Login dahulu!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_homeMenuActionPerformed

    private void backHomeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backHomeMenuItemActionPerformed
        // TODO add your handling code here:
        if (isLoggedIn) {
            contentScrollPane.setViewportView(new homePanel());
        } else {
            JOptionPane.showMessageDialog(this, "Silahkan Login dahulu!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_backHomeMenuItemActionPerformed

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        // TODO add your handling code here:
        if (isLoggedIn) {
            // Mengatur ulang status login agar bisa logout 
            setLoggedIn(false);
            // Ganti tampilan antarmuka pengguna kembali ke panel login
            contentScrollPane.setViewportView(new LoginPanel(contentScrollPane, this));
            JOptionPane.showMessageDialog(this, "Terima kasih telah menggunakan aplikasi!", "Logout", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Anda belum login, silahkan login dahulu!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem anggotaMenuItem;
    private javax.swing.JMenuItem backHomeMenuItem;
    private javax.swing.JScrollPane contentScrollPane;
    private javax.swing.JMenu entriMenu;
    private javax.swing.JMenu homeMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu logoutMenu;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JMenuItem nilaiMenuItem;
    // End of variables declaration//GEN-END:variables
}
